swagger: "2.0"
info:
  description: "This is a sample server Petstore server.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters."
  version: "1.0.0"
  title: "Swagger Petstore"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "petstore.swagger.io"
basePath: "/v2"
tags:
  - name: empty
    description: ---
schemes:
  - https
  - http
paths:

definitions:
  Token:
    type: object
    properties:
      Id:
        type: integer
      Token:
        type: string
      Waznosc:
        type: string
        format: data-time
    xml:
      name: Token

  Administrator:
    type: object
    properties:
      Prawa:
        type: string
    xml:
      name: Administrator

  Uzytkownik:
    type: object
    properties:
      Id:
        type: integer
      Imie:
        type: string
      Nazwisko:
        type: string
      Login:
        type: string
      Haslo:
        type: string
      Email:
        type: string
    xml:
      name: Uzytkownik

  Galeria:
    type: object
    properties:
      Id:
        type: integer
      Tytul:
        type: string
      Opis:
        type: string
      Data:
        type: string
        format: data-time
      Widocznosc:
        format: boolean
        default: true

  Tag:
    type: object
    properties:
      Id:
        type: integer
      Tekst:
        type: string

  Obraz:
    type: object
    properties:
      Id:
        type: string
      Tytul:
        type: string
      Opis:
        type: string
      Data:
        type: string
        format: data-time
      Nazwa Pliku:
        type: string
      Sciezka:
        type: string
      Rozmiar:
        type: integer

  Miniaturka:
    type: object
    properties:
      Typ:
        type: string

  Komentarz:
    type: object
    properties:
      Id:
        type: string
      Tresc:
        type: string
      Data:
        type: string
        format: data-time

externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"